//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptimLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погрешность по координате.
        /// </summary>
        internal static string LabelErrorInPointText {
            get {
                return ResourceManager.GetString("LabelErrorInPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погрешность по значению.
        /// </summary>
        internal static string LabelErrorInValueText {
            get {
                return ResourceManager.GetString("LabelErrorInValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во вычислений 1-го ограничения.
        /// </summary>
        internal static string LabelEvalsConst1Text {
            get {
                return ResourceManager.GetString("LabelEvalsConst1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во вычислений 2-го ограничения.
        /// </summary>
        internal static string LabelEvalsConst2Text {
            get {
                return ResourceManager.GetString("LabelEvalsConst2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во вычислений 3-го ограничения.
        /// </summary>
        internal static string LabelEvalsConst3Text {
            get {
                return ResourceManager.GetString("LabelEvalsConst3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во вычислений целевой функции.
        /// </summary>
        internal static string LabelEvalsTargetText {
            get {
                return ResourceManager.GetString("LabelEvalsTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число итераций.
        /// </summary>
        internal static string LabelIterationsText {
            get {
                return ResourceManager.GetString("LabelIterationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшая точка.
        /// </summary>
        internal static string LabelPointText {
            get {
                return ResourceManager.GetString("LabelPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        internal static string LabelValueText {
            get {
                return ResourceManager.GetString("LabelValueText", resourceCulture);
            }
        }
    }
}
